"""SQLAlchemy ORM models for database tables."""

import uuid
from datetime import datetime
from sqlalchemy import Column, String, Integer, Text, DateTime, ForeignKey, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.dialects.sqlite import JSON as SQLiteJSON

from app.models.database import Base


def generate_uuid():
    """Generate a UUID string."""
    return str(uuid.uuid4())


class Session(Base):
    """Session model - tracks each content generation request."""
    
    __tablename__ = "sessions"
    
    id = Column(String(36), primary_key=True, default=generate_uuid)
    created_at = Column(DateTime, default=datetime.utcnow)
    status = Column(String(20), default="pending")  # pending, processing, completed, failed
    grade = Column(Integer, nullable=False)
    topic = Column(String(255), nullable=False)
    total_attempts = Column(Integer, default=0)
    
    # Relationships
    generations = relationship("Generation", back_populates="session", cascade="all, delete-orphan")


class Generation(Base):
    """Generation model - stores content generated by Generator Agent."""
    
    __tablename__ = "generations"
    
    id = Column(String(36), primary_key=True, default=generate_uuid)
    session_id = Column(String(36), ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False)
    attempt_number = Column(Integer, nullable=False)
    explanation = Column(Text)
    mcqs = Column(JSON)  # Array of MCQ objects
    raw_response = Column(JSON)  # Full LLM response for debugging
    created_at = Column(DateTime, default=datetime.utcnow)
    feedback_used = Column(Text)  # Feedback from previous review if this is a retry
    
    # Relationships
    session = relationship("Session", back_populates="generations")
    review = relationship("Review", back_populates="generation", uselist=False, cascade="all, delete-orphan")


class Review(Base):
    """Review model - stores feedback from Reviewer Agent."""
    
    __tablename__ = "reviews"
    
    id = Column(String(36), primary_key=True, default=generate_uuid)
    generation_id = Column(String(36), ForeignKey("generations.id", ondelete="CASCADE"), nullable=False)
    status = Column(String(10), nullable=False)  # pass, fail
    feedback = Column(JSON)  # Array of feedback strings
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    generation = relationship("Generation", back_populates="review")
